export default {
    placeholder: require('../assets/images/placeholder.png'),
    captain0: require('../assets/images/captains/captain_0.png'),
    captain1: require('../assets/images/captains/captain_1.png'),
    captain2: require('../assets/images/captains/captain_2.png'),
    captain3: require('../assets/images/captains/captain_3.png'),
    captain4: require('../assets/images/captains/captain_4.png'),
    captain5: require('../assets/images/captains/captain_2.png'),
    car: require('../assets/images/captains/vehicles/3d-car.png'),
    auto: require('../assets/images/captains/vehicles/rickshaw.png'),
    bike: require('../assets/images/captains/vehicles/motorcycle.png'),
    requested: require('../assets/images/request.png'),
    accepted: require('../assets/images/accepted.png'),
    hold: require('../assets/images/hold.png'),
    searchLoader: require('../assets/images/loading.json'),
    rideAccept: require('../assets/images/ride_accept.png'),
    rideCancel: require('../assets/images/ride_cancel.png'),
    backgroundImage: require('../assets/images/bg1.png'),
    referBg:  require('../assets/images/refer_bg.png'),
    referGiftBox:  require('../assets/images/refer_gift_box.png'),
    pin: require('../assets/images/pin.png'),
    carYellow: require('../assets/images/car.png'),
    google: require('../assets/images/google.png'),
    captain:  require('../assets/images/captain_icon.png'),
    user:  require('../assets/images/group.png'),
    taxiDriver:  require('../assets/images/taxi-driver.png'),
    homeBanner: require('../assets/images/home_loader.png'),
    gettingStarted1:require('../assets/images/getting_started_1.png'),
    gettingStarted2:require('../assets/images/getting_started_2.png'),
    logo:require('../assets/images/logo.png')
}   