export default {
    placeholder: require('../assets/images/placeholder.png'),
    captain0: require('../assets/images/captains/captain_0.png'),
    captain1: require('../assets/images/captains/captain_1.png'),
    captain2: require('../assets/images/captains/captain_2.png'),
    captain3: require('../assets/images/captains/captain_3.png'),
    captain4: require('../assets/images/captains/captain_4.png'),
    captain5: require('../assets/images/captains/captain_2.png'),
    car: require('../assets/images/captains/vehicles/3d-car.png'),
    auto: require('../assets/images/captains/vehicles/rickshaw.png'),
    bike: require('../assets/images/captains/vehicles/motorcycle.png'),
    requested: require('../assets/images/request.png'),
    accepted: require('../assets/images/accepted.png'),
    hold: require('../assets/images/hold.png'),
    searchLoader: require('../assets/images/loading.json'),
    rideAccept: require('../assets/images/ride_accept.png'),
    rideCancel: require('../assets/images/ride_cancel.png'),
    backgroundImage: require('../assets/images/bg.jpeg'),
    pin: require('../assets/images/pin.png'),
    carYellow: require('../assets/images/car.png'),
}   