# Required for 16 KB memory page size support on Android 15+
android.useLegacyPackaging=false
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
FLIPPER_VERSION=0.182.0
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false
hermesEnabled=true

MYAPP_UPLOAD_STORE_FILE=apnidukandari-keystore.jks
MYAPP_UPLOAD_KEY_ALIAS=QGthc2FybGFyYXZpL2FwbmlkdWthbmRhcmk=
MYAPP_UPLOAD_STORE_PASSWORD=4d04b0a5bf5a4568a6ad5d5f0ba5f713
MYAPP_UPLOAD_KEY_PASSWORD=680fff5fab0b4fb198de8272fecf0816

# Silence AGP 8.4.2 warning for compileSdk 35
android.suppressUnsupportedCompileSdk=35
android.injected.llndk.pageSize=16384
